<?php

namespace Entities\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TableAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableAddressRepository extends EntityRepository
{
}