<?php

namespace Entities\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TableTest2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableTest2Repository extends EntityRepository
{
}