<?php

namespace Entities\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TableTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableTestRepository extends EntityRepository
{
}