<?php

namespace Entities\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TablePersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablePersonRepository extends EntityRepository
{
}